#!/usr/bin/env bash

BUILD_TAG="${CIRCLE_TAG:-${CIRCLE_BRANCH:-dev}-${CIRCLE_SHA1:-local}}"

mkdir -p output/packages

for PLATFORM in "chrome" "firefox"; do
  ARCHIVE="output/packages/tabsleeper-extension-${PLATFORM}-${BUILD_TAG}.zip"

  # Build the archive with the extension source
  zip -r $ARCHIVE \
    build/dist \
    static \
    icon \
    vendor

  # Include the platform specific manifest at the top level of the archive (-j)
  zip $ARCHIVE -j build/platform/$PLATFORM/manifest.json
done
